import { Instagram, Twitter, Activity, Linkedin } from "lucide-react";

export const USER_INTERESTS = [
  "Technology",
  "AI & Machine Learning",
  "Gaming",
  "Science",
  "Books & Literature",
  "Movies & Cinema",
  "Music",
  "Art & Design",
  "Travel & Adventure",
  "Food & Cooking",
  "Sports & Fitness",
  "Programming",
  "Startups & Entrepreneurship",
  "History",
  "Philosophy",
  "Nature & Outdoors",
  "Photography",
  "Writing",
  "Fashion & Style",
  "Space Exploration",
];

export const DEFAULT_PROFILE_PIC_URL =
  "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png";
export const DEFAULT_BOT_PLACEHOLDER_IMAGE_URL =
  "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9d/Iron_Man_Infobox.jpg/revision/latest?cb=20240802142023";
export // Extensive Mock Data
const mockData = {
  // User Profile
  user: {
    name: "Sarah Johnson",
    email: "sarah@creativestudio.com",
    avatar: "/professional-woman-diverse.png",
    role: "Social Media Manager",
    company: "Creative Studio",
    plan: "Pro",
    joinDate: "2023-01-15",
  },

  // ... (rest of the mockData remains the same)
  platforms: [
    {
      name: "Instagram",
      connected: true,
      followers: 45200,
      color: "#E4405F",
      icon: "📷",
      posts: 342,
    },
    {
      name: "Twitter/X",
      connected: true,
      followers: 12800,
      color: "#1DA1F2",
      icon: "🐦",
      posts: 1205,
    },
    {
      name: "Facebook",
      connected: true,
      followers: 8900,
      color: "#1877F2",
      icon: "📘",
      posts: 156,
    },
    {
      name: "LinkedIn",
      connected: true,
      followers: 3400,
      color: "#0A66C2",
      icon: "💼",
      posts: 89,
    },
    {
      name: "TikTok",
      connected: false,
      followers: 0,
      color: "#000000",
      icon: "🎵",
      posts: 0,
    },
    {
      name: "YouTube",
      connected: true,
      followers: 2100,
      color: "#FF0000",
      icon: "📺",
      posts: 23,
    },
  ],
  analytics: {
    totalFollowers: 72400,
    totalPosts: 1815,
    totalEngagement: 156780,
    avgEngagementRate: 4.2,
    monthlyGrowth: 12.5,
    weeklyReach: 89400,
    impressions: 234500,
    clicks: 12340,
    shares: 3450,
    saves: 2890,
    comments: 8920,
    likes: 45600,
    profileViews: 15600,
    videoViews: 89200,
    storyViews: 34500,
    mentionsCount: 156,
    hashtagReach: 45600,
    websiteClicks: 2340,
    emailSignups: 89,
    conversionRate: 3.8,
  },
  engagementData: [
    { name: "Mon", likes: 1200, comments: 80, shares: 45 },
    { name: "Tue", likes: 1900, comments: 120, shares: 67 },
    { name: "Wed", likes: 800, comments: 60, shares: 32 },
    { name: "Thu", likes: 2400, comments: 150, shares: 89 },
    { name: "Fri", likes: 3200, comments: 200, shares: 120 },
    { name: "Sat", likes: 2800, comments: 180, shares: 95 },
    { name: "Sun", likes: 2100, comments: 140, shares: 78 },
  ],
  growthData: [
    { month: "Jan", followers: 65000, posts: 45 },
    { month: "Feb", followers: 67200, posts: 52 },
    { month: "Mar", followers: 69800, posts: 48 },
    { month: "Apr", followers: 71500, posts: 55 },
    { month: "May", followers: 72400, posts: 49 },
    { month: "Jun", followers: 74100, posts: 58 },
  ],
  platformData: [
    { name: "Instagram", value: 45200, color: "#E4405F" },
    { name: "Twitter/X", value: 12800, color: "#1DA1F2" },
    { name: "Facebook", value: 8900, color: "#1877F2" },
    { name: "LinkedIn", value: 3400, color: "#0A66C2" },
    { name: "YouTube", value: 2100, color: "#FF0000" },
  ],
  recentPosts: [
    {
      id: 1,
      content: "Just launched our new product line! 🚀 What do you think?",
      platforms: ["Instagram", "Twitter/X", "Facebook"],
      status: "published",
      publishedAt: "2024-01-15T10:30:00Z",
      engagement: { likes: 234, comments: 45, shares: 12 },
      image: "/product-launch-excitement.png",
    },
    {
      id: 2,
      content: "Behind the scenes of our creative process ✨",
      platforms: ["Instagram", "LinkedIn"],
      status: "scheduled",
      scheduledFor: "2024-01-16T14:00:00Z",
      image: "/creative-workspace.png",
    },
    {
      id: 3,
      content: "Tips for better social media engagement 📈",
      platforms: ["Twitter/X", "LinkedIn"],
      status: "draft",
      engagement: { likes: 0, comments: 0, shares: 0 },
    },
  ],
  scheduledPosts: [
    {
      id: 4,
      content: "Monday motivation! Start your week strong 💪",
      platforms: ["Instagram", "Twitter/X"],
      scheduledFor: "2024-01-22T09:00:00Z",
      image: "/motivation-quote.jpg",
    },
    {
      id: 5,
      content: "New blog post: 10 Social Media Trends for 2024",
      platforms: ["LinkedIn", "Facebook"],
      scheduledFor: "2024-01-23T11:30:00Z",
    },
  ],
  team: [
    {
      id: 1,
      name: "Alex Chen",
      role: "Content Creator",
      avatar: "/thoughtful-asian-man.png",
      status: "online",
      lastActive: "2 min ago",
    },
    {
      id: 2,
      name: "Maria Rodriguez",
      role: "Graphic Designer",
      avatar: "/confident-latina-woman.png",
      status: "away",
      lastActive: "1 hour ago",
    },
    {
      id: 3,
      name: "David Kim",
      role: "Analytics Specialist",
      avatar: "/korean-man.png",
      status: "offline",
      lastActive: "3 hours ago",
    },
  ],
  workspaces: [
    {
      id: 1,
      name: "Creative Studio",
      description: "Main brand workspace",
      members: 8,
      posts: 156,
      color: "#8b5cf6",
      active: true,
    },
    {
      id: 2,
      name: "Client: TechCorp",
      description: "Technology client campaigns",
      members: 4,
      posts: 89,
      color: "#3b82f6",
      active: false,
    },
    {
      id: 3,
      name: "Personal Brand",
      description: "Sarah's personal content",
      members: 1,
      posts: 234,
      color: "#10b981",
      active: false,
    },
  ],
  templates: [
    {
      id: 1,
      name: "Product Launch",
      description: "Template for new product announcements",
      uses: 23,
      category: "Marketing",
      platforms: ["Instagram", "Twitter/X", "Facebook"],
    },
    {
      id: 2,
      name: "Behind the Scenes",
      description: "Showcase your creative process",
      uses: 45,
      category: "Engagement",
      platforms: ["Instagram", "LinkedIn"],
    },
    {
      id: 3,
      name: "Educational Tips",
      description: "Share knowledge and expertise",
      uses: 67,
      category: "Education",
      platforms: ["LinkedIn", "Twitter/X"],
    },
  ],
  aiSuggestions: [
    {
      type: "content",
      title: "Trending Hashtags",
      description: "#SocialMediaTips, #ContentCreation, #DigitalMarketing",
      confidence: 92,
    },
    {
      type: "timing",
      title: "Optimal Post Time",
      description: "Best engagement at 2:30 PM on weekdays",
      confidence: 87,
    },
    {
      type: "content",
      title: "Content Idea",
      description: "Share a carousel about social media myths vs facts",
      confidence: 94,
    },
  ],
  recentActivity: [
    {
      id: 1,
      type: "post_published",
      message: "Post published to Instagram and Twitter/X",
      timestamp: "2024-01-15T10:30:00Z",
      user: "Sarah Johnson",
    },
    {
      id: 2,
      type: "comment_received",
      message: "New comment on 'Product Launch' post",
      timestamp: "2024-01-15T09:45:00Z",
      user: "Alex Chen",
    },
    {
      id: 3,
      type: "team_joined",
      message: "David Kim joined the workspace",
      timestamp: "2024-01-15T08:20:00Z",
      user: "System",
    },
  ],
  performanceMetrics: [
    { metric: "Engagement Rate", value: "4.2%", change: "+0.8%", trend: "up" },
    { metric: "Reach", value: "89.4K", change: "+12.5%", trend: "up" },
    { metric: "Impressions", value: "234.5K", change: "+8.3%", trend: "up" },
    {
      metric: "Click-through Rate",
      value: "2.1%",
      change: "-0.3%",
      trend: "down",
    },
  ],
  allPosts: [
    {
      id: 1,
      content: "Just launched our new product line! 🚀 What do you think?",
      platforms: ["Instagram", "Twitter/X", "Facebook"],
      status: "published",
      publishedAt: "2024-01-15T10:30:00Z",
      engagement: { likes: 234, comments: 45, shares: 12, saves: 23 },
      image: "/product-launch-excitement.png",
      type: "image",
      reach: 12400,
      impressions: 18600,
    },
    {
      id: 2,
      content: "Behind the scenes of our creative process ✨",
      platforms: ["Instagram", "LinkedIn"],
      status: "published",
      publishedAt: "2024-01-14T14:00:00Z",
      engagement: { likes: 189, comments: 32, shares: 8, saves: 45 },
      image: "/creative-workspace.png",
      type: "image",
      reach: 9800,
      impressions: 14200,
    },
    {
      id: 3,
      content: "Tips for better social media engagement 📈 Thread below 👇",
      platforms: ["Twitter/X", "LinkedIn"],
      status: "published",
      publishedAt: "2024-01-13T09:15:00Z",
      engagement: { likes: 456, comments: 78, shares: 34, saves: 67 },
      type: "text",
      reach: 15600,
      impressions: 23400,
    },
    {
      id: 4,
      content: "Monday motivation! Start your week strong 💪",
      platforms: ["Instagram", "Twitter/X"],
      status: "published",
      publishedAt: "2024-01-12T09:00:00Z",
      engagement: { likes: 312, comments: 56, shares: 19, saves: 89 },
      image: "/motivation-quote.jpg",
      type: "image",
      reach: 11200,
      impressions: 16800,
    },
    {
      id: 5,
      content: "New blog post: 10 Social Media Trends for 2024 📝 Link in bio!",
      platforms: ["LinkedIn", "Facebook"],
      status: "published",
      publishedAt: "2024-01-11T11:30:00Z",
      engagement: { likes: 178, comments: 23, shares: 45, saves: 34 },
      type: "text",
      reach: 8900,
      impressions: 13400,
    },
    {
      id: 6,
      content: "Team meeting vibes! Planning amazing content for you 🎯",
      platforms: ["Instagram", "LinkedIn"],
      status: "published",
      publishedAt: "2024-01-10T16:45:00Z",
      engagement: { likes: 267, comments: 41, shares: 15, saves: 28 },
      image: "/thoughtful-asian-man.png",
      type: "image",
      reach: 10500,
      impressions: 15700,
    },
    {
      id: 7,
      content: "Quick tip: Use analytics to optimize your posting times! ⏰",
      platforms: ["Twitter/X", "LinkedIn"],
      status: "published",
      publishedAt: "2024-01-09T13:20:00Z",
      engagement: { likes: 389, comments: 67, shares: 28, saves: 56 },
      type: "text",
      reach: 14300,
      impressions: 21500,
    },
    {
      id: 8,
      content:
        "Celebrating our amazing community! Thank you for 70K+ followers 🎉",
      platforms: ["Instagram", "Facebook", "Twitter/X"],
      status: "published",
      publishedAt: "2024-01-08T12:00:00Z",
      engagement: { likes: 892, comments: 156, shares: 89, saves: 123 },
      image: "/confident-latina-woman.png",
      type: "image",
      reach: 25600,
      impressions: 38400,
    },
    {
      id: 9,
      content: "Weekend project: Redesigning our content calendar 📅",
      platforms: ["Instagram", "LinkedIn"],
      status: "published",
      publishedAt: "2024-01-07T15:30:00Z",
      engagement: { likes: 234, comments: 38, shares: 12, saves: 67 },
      type: "text",
      reach: 9200,
      impressions: 13800,
    },
    {
      id: 10,
      content: "Client spotlight: Amazing results with our social strategy! 📊",
      platforms: ["LinkedIn", "Twitter/X"],
      status: "published",
      publishedAt: "2024-01-06T10:15:00Z",
      engagement: { likes: 445, comments: 89, shares: 56, saves: 78 },
      image: "/korean-man.png",
      type: "image",
      reach: 16800,
      impressions: 25200,
    },
    {
      id: 11,
      content:
        "Pro tip: Engage with your audience within the first hour of posting! 💬",
      platforms: ["Twitter/X", "Instagram"],
      status: "published",
      publishedAt: "2024-01-05T08:45:00Z",
      engagement: { likes: 356, comments: 72, shares: 34, saves: 45 },
      type: "text",
      reach: 13400,
      impressions: 20100,
    },
    {
      id: 12,
      content: "Friday feeling! What's your favorite social media platform? 🤔",
      platforms: ["Instagram", "Facebook", "Twitter/X"],
      status: "published",
      publishedAt: "2024-01-04T17:00:00Z",
      engagement: { likes: 567, comments: 134, shares: 45, saves: 23 },
      type: "text",
      reach: 18900,
      impressions: 28400,
    },
    {
      id: 13,
      content: "Thursday thoughts: Consistency is key in social media! 🔑",
      platforms: ["Twitter/X", "LinkedIn"],
      status: "published",
      publishedAt: "2024-01-03T11:30:00Z",
      engagement: { likes: 298, comments: 52, shares: 21, saves: 38 },
      type: "text",
      reach: 11800,
      impressions: 17700,
    },
    {
      id: 14,
      content: "Workspace Wednesday: Our creative corner setup 🎨",
      platforms: ["Instagram", "Pinterest"],
      status: "published",
      publishedAt: "2024-01-02T14:15:00Z",
      engagement: { likes: 423, comments: 67, shares: 29, saves: 156 },
      image: "/creative-workspace.png",
      type: "image",
      reach: 13200,
      impressions: 19800,
    },
    {
      id: 15,
      content: "New Year, new content strategy! What are your 2024 goals? 🎯",
      platforms: ["Instagram", "Facebook", "LinkedIn"],
      status: "published",
      publishedAt: "2024-01-01T10:00:00Z",
      engagement: { likes: 678, comments: 123, shares: 67, saves: 89 },
      type: "text",
      reach: 21400,
      impressions: 32100,
    },
    {
      id: 16,
      content: "Year-end reflection: Thank you for an amazing 2023! 🙏",
      platforms: ["Instagram", "Twitter/X", "Facebook"],
      status: "published",
      publishedAt: "2023-12-31T18:00:00Z",
      engagement: { likes: 834, comments: 178, shares: 92, saves: 145 },
      image: "/professional-woman-diverse.png",
      type: "image",
      reach: 28900,
      impressions: 43400,
    },
    {
      id: 17,
      content: "Holiday marketing tips that actually work! 🎄",
      platforms: ["LinkedIn", "Twitter/X"],
      status: "published",
      publishedAt: "2023-12-20T09:30:00Z",
      engagement: { likes: 512, comments: 89, shares: 45, saves: 78 },
      type: "text",
      reach: 16700,
      impressions: 25100,
    },
    {
      id: 18,
      content: "Behind the brand: Meet our amazing team! 👥",
      platforms: ["Instagram", "LinkedIn"],
      status: "published",
      publishedAt: "2023-12-15T16:20:00Z",
      engagement: { likes: 389, comments: 67, shares: 23, saves: 45 },
      image: "/thoughtful-asian-man.png",
      type: "image",
      reach: 12300,
      impressions: 18500,
    },
  ],
  additionalMetrics: [
    {
      metric: "Profile Views",
      value: "15.6K",
      change: "+12.1%",
      trend: "up",
      icon: "👁️",
    },
    {
      metric: "Website Clicks",
      value: "2.34K",
      change: "+5.2%",
      trend: "up",
      icon: "🔗",
    },
    {
      metric: "Conversion Rate",
      value: "3.8%",
      change: "+1.2%",
      trend: "up",
      icon: "🎯",
    },
  ],
};

export const AnalyticsmockData = {
  overview: {
    totalReach: 2847392,
    totalEngagement: 184729,
    totalPosts: 156,
    avgEngagementRate: 6.49,
  },
  platformStats: [
    {
      platform: "Instagram",
      icon: Instagram,
      color: "bg-gradient-to-r from-purple-500 to-pink-500",
      followers: 45200,
      posts: 42,
      avgEngagementRate: 8.2,
      reach: 892340,
      impressions: 1234567,
      profileViews: 15670,
      change: 12.5,
      storyViews: 234567,
      storyCompletionRate: 67,
      saves: 3420,
      comments: 1890,
      likes: 15670,
      shares: 890,
    },
    {
      platform: "Twitter",
      icon: Twitter,
      color: "bg-blue-500",
      followers: 28900,
      posts: 67,
      avgEngagementRate: 4.8,
      reach: 567890,
      impressions: 890123,
      profileViews: 8920,
      change: -2.1,
      retweets: 1234,
      replies: 567,
      likes: 8920,
      newFollowers: 234,
    },
    {
      platform: "TikTok",
      icon: Activity,
      color: "bg-black",
      followers: 67800,
      posts: 23,
      avgEngagementRate: 12.4,
      reach: 1234567,
      impressions: 2345678,
      profileViews: 45670,
      change: 28.7,
      avgWatchTime: 45,
      videoCompletionRate: 78,
      shares: 2340,
      comments: 1890,
      likes: 23450,
    },
    {
      platform: "LinkedIn",
      icon: Linkedin,
      color: "bg-blue-600",
      followers: 12400,
      posts: 24,
      avgEngagementRate: 5.6,
      reach: 152595,
      impressions: 234567,
      profileViews: 3450,
      change: 8.3,
      shares: 234,
      comments: 156,
      likes: 1890,
      newFollowers: 89,
    },
  ],
  contentPerformance: [
    {
      type: "Video",
      posts: 45,
      avgEngagementRate: 12.3,
      avgReach: 25670,
      avgWatchTime: 42,
      completionRate: 68,
      bestPerforming: "Product demo videos",
    },
    {
      type: "Carousel",
      posts: 23,
      avgEngagementRate: 9.8,
      avgReach: 18920,
      avgSaves: 234,
      swipeRate: 78,
      bestPerforming: "Step-by-step tutorials",
    },
    {
      type: "Single Image",
      posts: 78,
      avgEngagementRate: 8.7,
      avgReach: 15670,
      avgSaves: 156,
      bestPerforming: "Behind-the-scenes content",
    },
    {
      type: "Stories",
      posts: 156,
      avgEngagementRate: 6.2,
      avgReach: 12340,
      completionRate: 67,
      replyRate: 4.8,
      bestPerforming: "Polls and questions",
    },
  ],
  hashtagAnalysis: [
    {
      tag: "#innovation",
      posts: 23,
      avgReach: 45670,
      avgEngagement: 8.9,
      impressions: 234567,
      topPost: "AI breakthrough announcement",
      trend: "up",
    },
    {
      tag: "#tech",
      posts: 18,
      avgReach: 38920,
      avgEngagement: 7.2,
      impressions: 189234,
      topPost: "New product launch",
      trend: "stable",
    },
    {
      tag: "#startup",
      posts: 15,
      avgReach: 29340,
      avgEngagement: 9.8,
      impressions: 156789,
      topPost: "Funding announcement",
      trend: "up",
    },
  ],
  audienceInsights: {
    demographics: {
      ageGroups: [
        { range: "18-24", percentage: 28, engagement: 9.2 },
        { range: "25-34", percentage: 42, engagement: 8.7 },
        { range: "35-44", percentage: 20, engagement: 7.1 },
        { range: "45+", percentage: 10, engagement: 6.8 },
      ],
      genderSplit: { male: 52, female: 48 },
    },
    deviceBreakdown: {
      mobile: 78,
      desktop: 22,
      mobileEngagement: 8.9,
      desktopEngagement: 6.4,
    },
  },
  sentimentAnalysis: {
    positive: 68,
    neutral: 24,
    negative: 8,
    topPositiveKeywords: ["amazing", "love", "great", "awesome", "perfect"],
    topNegativeKeywords: ["disappointed", "slow", "expensive", "confusing"],
    sentimentTrend: "improving",
  },
};
